FROM python:3.10.11-slim


WORKDIR /app


# Копируем файлы зависимостей
COPY requirements.txt .


# Устанавливаем зависимости Python
RUN pip install  -r requirements.txt

# Копируем все файлы проекта
COPY . .

# Указываем порт, который будет использоваться
EXPOSE 8001

# Команда для запуска приложения
CMD   alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8001
